#include<iostream>
using namespace std;
main()
{
	int a,b;
	cout<<"SUJAL SUVA "<<endl;
	cout<<"220130318034"<<endl;
	cout<<"Enter A ::";
	cin>>a;
	cout<<"Enter B ::";
	cin>>b;

	cout<<"\nSum of A+b is 		 	  ::"<<a+b;
	cout<<"\nSubstraction of A-b is   ::"<<a-b;
	cout<<"\nMultiplication of A*b is ::"<<a*b;
	cout<<"\nDivision of A/b is       ::"<<a/b;
	cout<<"\nModulo of A%b is         ::"<<a%b;

	
}

